@startmindmap

* 交易(订单)中心

** 支付单

** 订单

*** 订单项
*** 发货记录
*** 退货申请
*** 退货记录
*** 退款记录


** 申诉
*** 会员申诉
*** 商家申诉

** 订单评论
*** 得分(商品/物流/客服)
*** 评论图片

** 营销

*** 优惠券
**** 商家优惠券
***** 抵扣规则
***** 被领用记录
**** 平台优惠券
***** 抵扣规则
***** 被领用记录

*** 满减
*** 满赠
*** 团购
*** 限时折扣

** 财务结算

*** 结算

**** 订单分佣结算记录

**** 商家账期汇总结算记录
**** 商家账期汇总结算明细

**** 商家账期优惠券补贴汇总记录
**** 商家账期优惠券补贴汇总明细

*** 发票
**** 商家开出的票
**** 平台开出的票

@endmindmap