@startuml


 
class 支付单 {
    ID
    订单编号
    店铺
    物流费用
    物流公司
    物流单号
    单据创建时间
    单据结束时间
    单据确认时间
    操作员
    状态
    收货人姓名
    运单号
    收货地址
    配送类型
    发货单创建时间
}
 
class 订单 {
    ID
    订单号
    应付金额
    是否需要发票
    收货人
    订单总额
    支付方式
    收货人手机
    商品总额
    已支付金额
    收货人电话
    配送费用
    预存款
    收货地址
    订单状态
    下单时间
}
 
class 发货记录 {
    ID
    订单编号
    店铺
    物流费用
    物流公司
    物流单号
    单据创建时间
    单据结束时间
    单据确认时间
    操作员
    状态
    收货人姓名
    运单号
    收货地址
    配送类型
    发货单创建时间
}
 
class 退货申请 {
    ID
    订单编号
    退换货编号
    申请时间
    处理进度
    售后类型（退货、换货）
    订单编号
    所属商家
    申请售后原因
    申请描述


}
 
class 退货记录 {
    ID
    商品ID
    会员ID
    订单编号
    创建时间
}
 
class 退款记录 {
    ID
    商品ID
    会员ID
    订单编号
    退款金额
    创建时间
}
 
class 申诉记录 {
    ID
    会员ID
    商家ID
    申诉内容
    订单编号
    创建时间
}
 
class 订单评论 {
    ID
    会员ID
    评价分数
    评价内容
    订单编号
    创建时间
}
 
发货记录 "1" -- "1" 订单
退货申请 "1" -- "1" 订单
退货记录 "1" -- "1" 订单
退款记录 "1" -- "1" 订单
申诉记录 "1" -- "1" 订单
订单评论 "1" -- "1" 订单
支付单 "1" -- "1" 订单

 
class 发票 {
    ID
    发票编号
    会员ID
    商家ID
    开票公司
    金额
    开票时间
}

class 营销 {
    ID
    会员ID
    商品ID
    优惠时间
    创建时间
}
 
class 优惠券 {
    ID
    会员ID
    商家ID
    商品ID
    优惠额度
    发放数量
    优惠时间
    创建时间
}

class 满减 {
    ID
    会员ID
    商家ID
    商品ID
    优惠时间
    创建时间
}
 
class 满赠 {
    ID
    会员ID
    商家ID
    商品ID
    优惠时间
    创建时间
}
 
class 团购 {
    ID
    会员ID
    商家ID
    商品ID
    优惠时间
    创建时间
}

class 限时折扣 {
    ID
    会员ID
    商家ID
    商品ID
    优惠时间
    创建时间
}
 
class 结算 {
    ID
    平台ID
    商家ID
    金额
    创建时间
}
 
class 订单分佣结算记录 {
    ID
    平台ID
    商家ID
    订单编号
    金额
    创建时间
}
 
class 商家账期汇总结算记录 {
    ID
    平台ID
    商家ID
    金额
    创建时间
}
 
class 商家账期汇总结算明细 {
    ID
    平台ID
    商家ID
    金额
    创建时间
}
 
class 商家账期优惠券补贴汇总记录 {
    ID
    平台ID
    商家ID
    优惠券ID
    金额
    创建时间
}
 
class 商家账期优惠券补贴汇总明细 {
    ID
    平台ID
    商家ID
    优惠券ID
    金额
    创建时间
}


营销 "1" *-- "n" 优惠券
营销 "1" *-- "n" 满减
营销 "1" *-- "n" 满赠
营销 "1" *-- "n" 团购
营销 "1" *-- "n" 限时折扣

结算 "1" *-- "n" 订单分佣结算记录
结算 "1" *-- "n" 商家账期汇总结算记录
结算 "1" *-- "n" 商家账期汇总结算明细
结算 "1" *-- "n" 商家账期优惠券补贴汇总记录
结算 "1" *-- "n" 商家账期优惠券补贴汇总明细


结算 "1" *-- "n" 发票

营销 "n" *-- "n" 结算

订单 "1" *-- "1" 发票

订单 "1" *-- "n" 营销

订单 "n" *-- "1" 结算

@enduml

