@startmindmap

* 商品中心

** 类目
*** 公共商品参数组
**** 参数键值
*** 公共商品属性
*** 公共商品规格
** 品牌
** 商品标签
** 虚拟分类

** 商品素材库
** 商品spu
*** spu属性键值
*** spu参数组
**** spu参数键值
*** spu图片
*** 商品问答

*** 商品sku组
**** 商品sku值
***** 商品sku
****** sku价格

@endmindmap