@startuml
object 商家
object 商家入驻申请
object 商家账号
object 商家账号权限
object 商家账号操作日志
object 商家私域会员
object 店铺
object 图库
object 店铺分类
object 商家文章
商家入驻申请 "1" o-- "1" 商家
商家账号 "n" --* "1" 商家
商家账号权限 "n" --* "1" 商家账号
商家账号操作日志 "n" --* "1" 商家账号
店铺 "n" --* "1" 商家
店铺 "1" *-- "n" 店铺分类
图库 "n" o-- "1" 商家
商家私域会员 "n" --* "1" 商家
商家文章 "n" --* "1" 商家
@enduml

