@startuml
title 会员和商家数据来源
== ==
终端 -> B2C会员:注册
终端 -> B2C商家: POS门店
B2C商家 -> B2B会员:快捷申请
B2C商家 -> B2B商家:快捷申请
终端 -> B2B会员:外部会员PC资料审核注册
终端 -> B2B商家:PC资料审核
B2B商家 -->终端:生成链接或二维码
终端 ->B2B会员:扫码私域门店链接|二维码
== ==
@enduml