@startmindmap

* 基础服务中心
** 消息公告
*** 消息
**** 会员消息
**** 商家消息

*** 公告
**** 平台公告
**** 会员公告
**** 商家公告

*** 意见反馈
**** 会员意见反馈
**** 商家意见反馈


** 站点
*** 站点基本信息
**** PC端配置
**** 移动端配置
***** 2B商城移动端配置
***** 2C商城移动端配置

*** 文章类目
**** 2B商城类目
***** 2B商城文章
**** 2C商城类目
***** 2B商城文章

** 装修配置
*** banner
**** PC端
***** 首页banner
***** 店铺banner
***** 分类专题banner

**** 移动端
***** 首页banner
***** 店铺banner
***** 分类专题banner


*** 店铺装修
**** 多商品展示配置表
**** 通栏广告图
**** 店铺导航菜单

*** 商家登录背景图


@endmindmap