@startuml

object 消息公告中心
object 商家消息
object 会员消息
object 公告
object 意见反馈

消息公告中心 *-- 商家消息
消息公告中心 *-- 会员消息
商家消息 "n"-- "m" 会员消息
消息公告中心 *-- 公告
消息公告中心 *-- 意见反馈


object 站点图片

object 文章

object 文章类目

object 站点

站点 *-- 文章
站点 *-- 站点图片
站点 *-- 文章类目
文章类目    ..> 文章


object 装修中心
object banner
object 商品图片
object 背景图片
object 导航菜单
object 多商品展示
object 通栏广告图

banner --* 装修中心
商品图片 --* 装修中心
背景图片 --* 装修中心
导航菜单 --* 装修中心
多商品展示 -- 商品图片
通栏广告图 -- 商品图片
导航菜单  ..> 商品图片

@enduml